//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int id { get; set; }
        public string hostId { get; set; }
        public string friendId { get; set; }
        public string chatId { get; set; }
        public string BlockOpetion { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
