//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.UnitArrangement = new HashSet<UnitArrangement>();
        }
    
        public int semesterId { get; set; }
        public string semester1 { get; set; }
    
        public virtual ICollection<UnitArrangement> UnitArrangement { get; set; }
    }
}
