//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyBuddyDaEntities1 : DbContext
    {
        public StudyBuddyDaEntities1()
            : base("name=StudyBuddyDaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Convener> Convener { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UnitArrangement> UnitArrangement { get; set; }
        public virtual DbSet<UnitTaken> UnitTaken { get; set; }
    }
}
