//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Chat = new HashSet<Chat>();
            this.Friend = new HashSet<Friend>();
            this.Friend1 = new HashSet<Friend>();
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
            this.UnitTaken = new HashSet<UnitTaken>();
        }
    
        public string studentId { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public string logonStatus { get; set; }
        public string vertificationCheck { get; set; }
        public Nullable<double> LocationX { get; set; }
        public Nullable<double> LocationY { get; set; }
        public string managerForbid { get; set; }
    
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual ICollection<Friend> Friend { get; set; }
        public virtual ICollection<Friend> Friend1 { get; set; }
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<Request> Request1 { get; set; }
        public virtual ICollection<UnitTaken> UnitTaken { get; set; }
    }
}
