//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.UnitArrangement = new HashSet<UnitArrangement>();
            this.UnitTaken = new HashSet<UnitTaken>();
        }
    
        public int unitCode { get; set; }
        public string unitName { get; set; }
        public int facultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<UnitArrangement> UnitArrangement { get; set; }
        public virtual ICollection<UnitTaken> UnitTaken { get; set; }
    }
}
