//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitArrangement
    {
        public int Id { get; set; }
        public int unitCode { get; set; }
        public int semesterId { get; set; }
        public int convenerId { get; set; }
    
        public virtual Convener Convener { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
